### PR TITLE
(SIMP-4009) Add support for Puppet 5 and OEL

### PR DESCRIPTION
**Pull request by jeefberkey**
SIMP-4009 #comment update simp_grafana

### CODE REVIEW

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-simp_grafana/pipelines/28648072

**Comment by jeefberkey** [comment]
All acceptance tests fail but that's ok https://gitlab.com/simp/pupmod-simp-simp_grafana/pipelines/28653553

**Comment by ayohrling** [comment]
What is the reasoning behind the failure? It looks like the failures are valid, as in the code isn't setting up a server as expected that can be logged into?

**Comment by trevor-vaughan** [comment]
Hmm...I thought we fixed this? IIRC, this is because Grafana can't handle the ciphers required by our default OpenLDAP setup.

**Comment by trevor-vaughan** [comment]
Yeah, I lowered the OpenLDAP ciphers in the tests and everything passes now. Hopefully this will get fixed in Grafana soon.

**Comment by trevor-vaughan** [comment]
:heavy_check_mark:   https://gitlab.com/simp/pupmod-simp-simp_grafana/pipelines/29086585

**Review by trevor-vaughan — APPROVED** [review]

**Pull request merged**
