### PR TITLE
(SIMP-4941) Fix systemd fixtures

### PR DESCRIPTION
**Pull request by jeefberkey**
The acceptance tests are broken due to
https://simp-project.atlassian.net/browse/SIMP-4032

SIMP-4941 #comment simp_grafana fixed

### CODE REVIEW

**Comment by jeefberkey** [comment]
:warning: https://gitlab.com/simp/pupmod-simp-simp_grafana/pipelines/23888813

**Comment by trevor-vaughan** [comment]
@jeefberkey From the grafana logs:

```
 error="LDAP Result Code 13 \"Confidentiality Required\": stronger TLS confidentiality required"
```

**Comment by trevor-vaughan** [comment]
Per https://community.grafana.com/t/getting-connection-reset-when-using-ldaps/1146, we may need to fall back to `stunnel`

**Comment by jeefberkey** [comment]
@trevor-vaughan if there is already a relevant ticket, should that hold up this PR?

**Review by trevor-vaughan — APPROVED** [review]

**Pull request merged**
